### ISSUE TITLE
npm install fails with "(buble plugin) CompileError: for...of statements are not supported."

### ISSUE THREAD

**Issue by mikeu** [KoRiGaN/Vue2Leaflet#366]
### Description
An error is thrown during `npm install`. I have experienced this on my own Windows machine, and seen the same output from Travis while attempting to run automated tests on a PR.

#### Steps to Reproduce
Clone the repo, and run `npm install`.

#### Expected Results
No error is thrown and the installation completes successfully.

#### Actual Results
The initial installation of dependencies succeeds, all tests pass, then while rollup is running the first dozen or so components succeed before the following error is thrown while processing `LMap`:
```
./src/components/LMap.vue → dist/components/LMap.js...
[!] (buble plugin) CompileError: for...of statements are not supported. Use `transforms: { forOf: false }` to skip transformation and disable this error, or `transforms: { dangerousForOf: true }` if you know what you're doing (165:6)
src/components/LMap.vue?rollup-plugin-vue=script.js (165:6)
161 :   methods: {
162 :     registerLayerControl (lControlLayers) {
163 :       this.layerControl = lControlLayers;
164 :       this.mapObject.addControl(lControlLayers.mapObject);
165 :       for (var layer of this.layersToAdd) {
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error
    at Node.initialise (/home/travis/build/KoRiGaN/Vue2Leaflet/node_modules/buble/src/program/types/ForOfStatement.js:8:10)
    at body.forEach.node (/home/travis/build/KoRiGaN/Vue2Leaflet/node_modules/buble/src/program/BlockStatement.js:41:34)
    at Array.forEach (<anonymous>)
    at Node.initialise (/home/travis/build/KoRiGaN/Vue2Leaflet/node_modules/buble/src/program/BlockStatement.js:41:13)
    at Node.initialise (/home/travis/build/KoRiGaN/Vue2Leaflet/node_modules/buble/src/program/Node.js:88:11)
    at Node.initialise (/home/travis/build/KoRiGaN/Vue2Leaflet/node_modules/buble/src/program/types/FunctionExpression.js:18:9)
    at Node.initialise (/home/travis/build/KoRiGaN/Vue2Leaflet/node_modules/buble/src/program/Node.js:88:11)
    at Node.initialise (/home/travis/build/KoRiGaN/Vue2Leaflet/node_modules/buble/src/program/types/Property.js:12:9)
    at value.forEach.node (/home/travis/build/KoRiGaN/Vue2Leaflet/node_modules/buble/src/program/Node.js:86:40)
    at Array.forEach (<anonymous>)
    at Node.initialise (/home/travis/build/KoRiGaN/Vue2Leaflet/node_modules/buble/src/program/Node.js:86:11)
    at Node.initialise (/home/travis/build/KoRiGaN/Vue2Leaflet/node_modules/buble/src/program/Node.js:88:11)
    at Node.initialise (/home/travis/build/KoRiGaN/Vue2Leaflet/node_modules/buble/src/program/types/Property.js:12:9)
    at value.forEach.node (/home/travis/build/KoRiGaN/Vue2Leaflet/node_modules/buble/src/program/Node.js:86:40)
    at Array.forEach (<anonymous>)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue2-leaflet@2.0.2 build: `rollup -c --environment NODE_ENV:production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue2-leaflet@2.0.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-04-04T16_45_22_248Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue2-leaflet@2.0.2 prepare: `npm run lint && npm run test && npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue2-leaflet@2.0.2 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-04-04T16_45_22_295Z-debug.log
The command "npm install" failed and exited with 1 during .
```

**Comment by DonNicoJs** [comment]
@mikeu thanks! I will take a look at this tomorrow!

**Comment by fodger** [comment]
Hi,
Exactly same issue for me.

Thanks a lot for your help.

**Comment by DonNicoJs** [comment]
@fodger @mikeu fixed the issue, I was a bit sloppy there. Travis builds are fixed too now.
Thanks again!
