### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by nealmiao** [KoRiGaN/Vue2Leaflet#6]
enter "npm run dev", then open http://localhost:8080/examples/index.html in browser, dose not work.
vue2-leaflet.js:71Uncaught ReferenceError: require is not defined
    at eval (eval at <anonymous> (http://localhost:8080/dist/vue2-leaflet.js:71:2), <anonymous>:1:18)
    at Object.<anonymous> (http://localhost:8080/dist/vue2-leaflet.js:71:2)
    at __webpack_require__ (http://localhost:8080/dist/vue2-leaflet.js:30:30)
    at Object.eval (eval at <anonymous> (http://localhost:8080/dist/vue2-leaflet.js:65:2), <anonymous>:1:66)
    at eval (eval at <anonymous> (http://localhost:8080/dist/vue2-leaflet.js:65:2), <anonymous>:130:30)
    at Object.<anonymous> (http://localhost:8080/dist/vue2-leaflet.js:65:2)
    at __webpack_require__ (http://localhost:8080/dist/vue2-leaflet.js:30:30)
    at Object.<anonymous> (http://localhost:8080/dist/vue2-leaflet.js:57:2)
    at __webpack_require__ (http://localhost:8080/dist/vue2-leaflet.js:30:30)
    at http://localhost:8080/dist/vue2-leaflet.js:50:18(anonymous function) @ external "url"?caec:1(anonymous function) @ vue2-leaflet.js:71__webpack_require__ @ vue2-leaflet.js:30(anonymous function) @ client?8d8f:1(anonymous function) @ client?d013:128(anonymous function) @ vue2-leaflet.js:65__webpack_require__ @ vue2-leaflet.js:30(anonymous function) @ vue2-leaflet.js:57__webpack_require__ @ vue2-leaflet.js:30(anonymous function) @ vue2-leaflet.js:50(anonymous function) @ vue2-leaflet.js:53webpackUniversalModuleDefinition @ vue2-leaflet.js:9(anonymous function) @ vue2-leaflet.js:10
Leaflet.Icon.Glyph.js:4 Uncaught ReferenceError: L is not defined(…)(anonymous function) @ Leaflet.Icon.Glyph.js:4
index.html:139 Uncaught ReferenceError: L is not defined(…)

**Comment by nealmiao** [comment]
It works, many thanks
